### PR TITLE
Add cfn-nag parser

### PR DESCRIPTION
**Pull request by spockNinja**
I love Lintly! 😍 

Here's another parser for a different CloudFormation linter that I would like to use.

So far, I have added the parser, some tests, and a link to the linter in the README.

### CODE REVIEW

**Comment by spockNinja** [comment]
I had some linting errors. I think fixing them up will get travis to let me merge.

However, there was also this error, which is not related to my PR.

```
lintly.backends.errors.GitClientError: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

**Comment by spockNinja** [comment]
Nevermind, looks like it won't pass after all. I think it's still trying to send a commit status.

**Comment by grantmcconnaughey** [comment]
Thanks for the PR, @spockNinja! I'm pretty sure I recently deleted the API token that Travis CI was using from my account because I thought it was not being used. I just recreated this token and I'm re-running the build now.

**Comment by grantmcconnaughey** [comment]
It doesn't seem to be working...apologies for the spam from Travis while I get this fixed.

**Comment by grantmcconnaughey** [comment]
Ah, Travis doesn't include encrypted environment variables in PRs that come from forked repos... https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

Screw it, I'm merging this one as-is. 😄

**Comment by grantmcconnaughey** [comment]
@spockNinja Lintly 0.4.1 has been released on PyPI: https://pypi.org/project/lintly/0.4.1/

**Pull request merged**
